---
name: dockerhub-description

# This workflow requires a DOCKERHUB_PASSWORD secret to be defined in the GitHub
# repository settings.

on:
  push:
    branches: [main]
    paths:
      - dockerhub-description.md
      - .github/workflows/dockerhub-description.yml

jobs:
  dockerhub-description:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Update repo description
        uses: peter-evans/dockerhub-description@v3
        with:
          username: dmotte
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          repository: dmotte/desktainer
          short-description: ${{ github.event.repository.description }}
          readme-filepath: dockerhub-description.md
