---
name: release

# This workflow requires a DOCKERHUB_PASSWORD secret to be defined in the GitHub
# repository settings.

on:
  push:
    branches: [main]
    paths:
      - build/**
      - .github/workflows/release.yml
  schedule:
    # Runs automatically on the 27th of every month at 04:30 UTC
    - cron: "30 04 27 * *"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: dmotte
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Get version number based on current date and time
        id: get-version
        run: echo "version=$(date +%Y.%m.%d.%H%M)" >> $GITHUB_OUTPUT

      - name: Build and push
        id: docker-build
        uses: docker/build-push-action@v4
        with:
          context: build
          platforms: linux/386, linux/amd64, linux/arm/v6, linux/arm/v7, linux/arm64
          push: true
          tags: dmotte/desktainer:latest,dmotte/desktainer:${{ steps.get-version.outputs.version }}

      - name: Image digest
        run: echo ${{ steps.docker-build.outputs.digest }}
